# Runs docker container with production settings.

services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    environment:
      # Set to False in production to hide detailed error pages
      - DJANGO_DEBUG=False
      # Appended to ALLOWED_HOSTS django settings
      - CUSTOM_DOMAIN=${CUSTOM_DOMAIN:-}
      # Path to SQLite database file
      - DJANGO_DB_PATH=/app/data/db.sqlite3
    restart: ${RESTART_POLICY:-no}
